# Generated by Django 5.1.1 on 2024-10-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
