# Generated by Django 5.1.1 on 2024-10-03 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_rating', '0002_remove_comment_user_remove_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments_rating.product'),
        ),
    ]
